AWSTemplateFormatVersion: '2010-09-09'
Description: n8n on Lightsail (Amazon Linux 2023) + Nginx + Certbot (automated)

Parameters:
  InstanceName:
    Type: String
    Default: n8n-instance
    Description: Name of the Lightsail instance
  AvailabilityZone:
    Type: String
    Default: us-east-1a
    Description: Availability zone for the instance (e.g., us-east-1a)
  BlueprintId:
    Type: String
    Description: The blueprint ID for the instance (e.g., amazon_linux_2023)
    Default: amazon_linux_2023
  BundleId:
    Type: String
    Description: The bundle ID for the instance (e.g., small_3_0)
    Default: small_3_0
  StaticIpName:
    Type: String
    Description: Name of the static IP to be created and attached to the instance
    Default: n8n-ip-address
  DBUser:
    Type: String
    Description: PostgreSQL database username
    Default: admin
  DBPassword:
    Type: String
    Description: PostgreSQL database password
    NoEcho: true
    Default: admin
  Domain:
    Type: String
    Description: The domain name to be used for n8n (e.g., example.com)
  Email:
    Type: String
    Description: The email address to be used for SSL certificate registration

Resources:
  Instance:
    Type: AWS::Lightsail::Instance
    Properties:
      InstanceName: !Ref InstanceName
      BlueprintId: !Ref BlueprintId
      BundleId: !Ref BundleId
      Location:
        AvailabilityZone: !Ref AvailabilityZone
      Networking:
        Ports:
          - AccessDirection: inbound
            CommonName: HTTPS
            Protocol: tcp
            FromPort: 443
            ToPort: 443
            AccessFrom: 0.0.0/0
            AccessType: Public
          - AccessDirection: inbound
            CommonName: HTTP
            Protocol: tcp
            FromPort: 80
            ToPort: 80
            AccessFrom: 0.0.0/0
            AccessType: Public
          - AccessDirection: inbound
            CommonName: SSH
            Protocol: tcp
            FromPort: 22
            ToPort: 22
            AccessFrom: 0.0.0/0
            AccessType: Public
      UserData: !Sub |
        #!/bin/bash
        set -euo pipefail

        echo "[INFO] Starting instance bootstrap..."
        
        # ------------------------------------------------------------------
        # Update the system and install necessary packages
        # ------------------------------------------------------------------
        sudo dnf update -y

        echo "[INFO] Downloading and executing setup script from GitHub..."

        # ------------------------------------------------------------------
        # Download whatsapp-chatbot setup script from GitHub and execute it
        # ------------------------------------------------------------------
        mkdir -p /opt/n8n
        curl -L https://github.com/JoseLuisSR/whatsapp-chatbot/archive/refs/heads/develop.zip -o /opt/n8n/whatsapp-chatbot.zip
        unzip /opt/n8n/whatsapp-chatbot.zip -d /opt/n8n/
        chmod +x /opt/n8n/whatsapp-chatbot-develop/aws/bootstrap.sh
        /opt/n8n/whatsapp-chatbot-develop/aws/bootstrap.sh ${Domain} ${Email} ${DBUser} ${DBPassword}
        
        echo "[INFO] Bootstrap finished."

  StaticIp:
    Type: AWS::Lightsail::StaticIp
    Properties:
      StaticIpName: !Ref StaticIpName
      AttachedTo: !Ref Instance