AWSTemplateFormatVersion: '2010-09-09'
Description: n8n on Lightsail (Amazon Linux 2023) + Nginx + Certbot (automated)

Parameters:
  InstanceName:
    Type: String
    Default: n8n-instance-2
  KeyPairName:
    Type: String
    Default: n8n-host-aws
  AvailabilityZone:
    Type: String
    Default: us-east-1a
  BlueprintId:
    Type: String
    Default: amazon_linux_2023
  BundleId:
    Type: String
    Default: small_3_0

Resources:
  Instance:
    Type: AWS::Lightsail::Instance
    Properties:
      InstanceName: !Ref InstanceName
      BlueprintId: !Ref BlueprintId
      BundleId: !Ref BundleId
      KeyPairName: !Ref KeyPairName
      Location:
        AvailabilityZone: !Ref AvailabilityZone
      Networking:
        Ports:
          - AccessDirection: inbound
            CommonName: HTTPS
            Protocol: tcp
            FromPort: 443
            ToPort: 443
            AccessFrom: 0.0.0/0
            AccessType: Public
          - AccessDirection: inbound
            CommonName: HTTP
            Protocol: tcp
            FromPort: 80
            ToPort: 80
            AccessFrom: 0.0.0/0
            AccessType: Public
          - AccessDirection: inbound
            CommonName: SSH
            Protocol: tcp
            FromPort: 22
            ToPort: 22
            AccessFrom: 0.0.0/0
            AccessType: Public
      UserData: |
        #!/bin/bash
        set -euo pipefail

        echo "[INFO] Starting instance bootstrap..."
        
        # ------------------------------------------------------------------
        # Update the system and install necessary packages
        # ------------------------------------------------------------------
        sudo dnf update -y

        echo "[INFO] Downloading and executing setup script from GitHub..."

        # ------------------------------------------------------------------
        # Download whatsapp-calendar-bot setup script from GitHub and execute it
        # ------------------------------------------------------------------
        curl -L https://github.com/JoseLuisSR/whatsapp-calendar-bot/archive/refs/heads/develop.zip -o /tmp/whatsapp-calendar-bot.zip
        unzip /tmp/whatsapp-calendar-bot.zip -d /tmp/
        chmod +x /tmp/whatsapp-calendar-bot-develop/aws/n8n-setup.sh
        /tmp/whatsapp-calendar-bot-develop/aws/n8n-setup.sh
        
        echo "[INFO] Bootstrap finished."

  StaticIp:
    Type: AWS::Lightsail::StaticIp
    Properties:
      StaticIpName: n8n-static-ip-address
      AttachedTo: !Ref Instance